# Generated by Django 5.2.4 on 2025-07-22 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('cnic_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('driving_license_no', models.CharField(blank=True, max_length=15, null=True)),
                ('accountno', models.CharField(blank=True, max_length=20, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
                ('live_photo', models.BinaryField(blank=True, null=True)),
                ('cnic_front_image', models.BinaryField(blank=True, null=True)),
                ('cnic_back_image', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('driving_license_front', models.BinaryField(blank=True, null=True)),
                ('driving_license_back', models.BinaryField(blank=True, null=True)),
                ('accountqr', models.BinaryField(blank=True, null=True)),
                ('driver_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('passenger_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}-\\d{1,4}(-[A-Z])?$', 'Enter a valid Pakistani vehicle plate, e.g. "ABC-1234" or "AB-123".')], verbose_name='Registration Number')),
                ('vehicle_type', models.CharField(choices=[('TW', 'Two Wheeler'), ('FW', 'Four Wheeler')], default='TW', max_length=2, verbose_name='Type')),
                ('color', models.CharField(blank=True, max_length=30)),
                ('photo_front', models.BinaryField(blank=True, null=True)),
                ('photo_back', models.BinaryField(blank=True, null=True)),
                ('documents_image', models.BinaryField(blank=True, null=True, verbose_name='Vehicle Documents (Card/EFI/Debit)')),
                ('seats', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Seats')),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='lets_go.usersdata', verbose_name='User')),
            ],
        ),
    ]
