# Generated by Django 5.2.4 on 2025-07-24 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='cnic_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format 36603-0269853-9', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 92XXXXXXXXXX (country code required)', regex='^\\92\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('BANNED', 'Banned')], default='PENDING', max_length=10),
        ),
    ]
