# Generated by Django 5.0.12 on 2025-07-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0003_alter_usersdata_phone_no_route_routestop_farematrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fare_calculation',
            field=models.JSONField(blank=True, default=dict, help_text='Complete frontend fare calculation breakdown'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total calculated distance from frontend', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Total calculated duration from frontend', null=True),
        ),
        migrations.CreateModel(
            name='TripStopBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_order', models.IntegerField(help_text='Order of pickup stop')),
                ('to_stop_order', models.IntegerField(help_text='Order of drop-off stop')),
                ('from_stop_name', models.CharField(help_text='Name of pickup stop', max_length=100)),
                ('to_stop_name', models.CharField(help_text='Name of drop-off stop', max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance between stops in kilometers', max_digits=8)),
                ('duration_minutes', models.IntegerField(help_text='Estimated duration between stops in minutes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this route segment', max_digits=10)),
                ('from_latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude of pickup stop', max_digits=10, null=True)),
                ('from_longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude of pickup stop', max_digits=11, null=True)),
                ('to_latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude of drop-off stop', max_digits=10, null=True)),
                ('to_longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude of drop-off stop', max_digits=11, null=True)),
                ('price_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed price calculation factors for this segment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_breakdowns', to='lets_go.trip')),
            ],
            options={
                'ordering': ['trip', 'from_stop_order'],
                'indexes': [models.Index(fields=['trip'], name='lets_go_tri_trip_id_b71f29_idx'), models.Index(fields=['from_stop_order'], name='lets_go_tri_from_st_d393be_idx'), models.Index(fields=['to_stop_order'], name='lets_go_tri_to_stop_2aafd4_idx')],
                'unique_together': {('trip', 'from_stop_order', 'to_stop_order')},
            },
        ),
    ]
