# Generated by Django 5.2.5 on 2025-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0004_trip_fare_calculation_trip_total_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='gender_preference',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', help_text='Gender preference for this trip (Male, Female, Any)', max_length=10),
        ),
    ]
