# Generated by Django 4.2.7 on 2025-01-15 12:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0005_trip_gender_preference'),
    ]

    operations = [
        # Add bargaining fields to Trip model
        migrations.AddField(
            model_name='trip',
            name='is_negotiable',
            field=models.BooleanField(default=True, help_text='Whether the driver is open to price negotiation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='minimum_acceptable_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fare driver is willing to accept', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bargaining_history',
            field=models.JSONField(blank=True, default=list, help_text='History of price negotiations for this trip'),
        ),
        
        # Add bargaining fields to Booking model
        migrations.AddField(
            model_name='booking',
            name='original_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original fare before negotiation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiated_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed fare after negotiation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bargaining_status',
            field=models.CharField(choices=[('NO_NEGOTIATION', 'No Negotiation'), ('PENDING', 'Pending Driver Response'), ('ACCEPTED', 'Accepted by Driver'), ('REJECTED', 'Rejected by Driver'), ('COUNTER_OFFER', 'Driver Counter Offer')], default='NO_NEGOTIATION', help_text='Current status of price negotiation', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Passenger's proposed fare", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_response',
            field=models.TextField(blank=True, help_text="Driver's response to passenger's offer", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the negotiation', null=True),
        ),
    ]
