# Generated by Django 5.2.5 on 2025-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0007_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True),
        ),
    ]
