# Generated by Django 5.2.5 on 2025-09-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0008_usersdata_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='lets_go.usersdata')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='lets_go.usersdata')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='lets_go.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip'], name='lets_go_tri_trip_id_7c61fd_idx'), models.Index(fields=['blocked_user'], name='lets_go_tri_blocked_21ac25_idx')],
                'unique_together': {('trip', 'blocked_user')},
            },
        ),
    ]
